language: cpp

dist: bionic

cache: apt

compiler:
    - gcc

env:
    global:
        - MAKEFLAGS="-j2"

sudo: required

before_install:
    - ./travis_install_capstone.sh

before_script:
    - mkdir build && cd build && cmake ..

script:
    - make

os:
    - linux

addons:
    apt:
        packages:
            - build-essential
            - libboost-dev
            - cmake
            - qt5-default
            - qtbase5-dev-tools
            - qttools5-dev-tools
            - qttools5-dev
			- libqt5xmlpatterns5-dev
