version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Antialiasing
  - CLASSINFO
  - debuggee
  - demangled
  - DEMANGLING
  - Doubleword
  - doublewords
  - DWORD
  - DWORDS
  - ELFCLASS
  - ELFDATA
  - ELFOSABI
  - eteran
  - Fabien
  - hexview
  - Kabatsayev
  - konsole
  - Mercês
  - METATYPE
  - Mohd
  - nasm
  - Nicoleau
  - nofork
  - Noto
  - Olly
  - Ollydbg
  - Opfer
  - Pixmap
  - Polyline
  - qcommonstyle
  - qgetenv
  - qlonglong
  - qobject
  - qsnprintf
  - Quadword
  - quadwords
  - qulonglong
  - QWORD
  - QWORDS
  - Ruslan
  - Scrollbars
  - Shahril
  - Sorokin
  - stepover
  - tbyte
  - Teran
  - xmmword
  - yasm
  - ymmword
  - zmmword
ignoreWords: []
import: []
